
name: auto-test
on:
  push:
    branches: ["main"]
jobs:
  # Test on Ubuntu
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake zlib1g-dev libboost-all-dev libxml2-dev libunwind-dev libgoogle-perftools-dev libspdlog-dev
      - name: Cache wiredtiger
        uses: actions/cache@v2
        with:
          path: /tmp/wiredtiger
          key: ${{ runner.os }}-wiredtiger-${{ hashFiles('**/auto-test.yaml') }}
      - name: Build wiredtiger
        run: |
          if [ ! -d "/tmp/wiredtiger" ]; then
            git clone https://github.com/wiredtiger/wiredtiger.git /tmp/wiredtiger
            cd /tmp/wiredtiger
            mkdir build && cd build
            cmake ../.
            make -j$(nproc)
            sudo make install
          fi
      - name: Run tests
        run: |
          mkdir build && cd build && cmake ..
          make -j$(nproc)
          ctest --output-on-failure -R "vulcan-test.*"